# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/rtwo/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),rtwo)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,eaf04223b322910dfdcd8c285b0e50c15cc6af24)
$(call add-radio-file-sha1-checked,radio/modem.img,d1f4c4dc88aa5ec551e5a2cdc4948745a6949d93)
$(call add-radio-file-sha1-checked,radio/abl.img,35a294087959e06ca23b7774ac6b9a2016feb2c3)
$(call add-radio-file-sha1-checked,radio/aop.img,8c975192e701d668cc88f67a070ed767ba9850d4)
$(call add-radio-file-sha1-checked,radio/cpucp.img,35b007404e5a2344e188effb3a2a81bff58a0a69)
$(call add-radio-file-sha1-checked,radio/devcfg.img,06f51893242bdc6e50e36e0be64e13c11def958c)
$(call add-radio-file-sha1-checked,radio/dsp.img,1ab46f7755535aacfa472cbccb3fb078d6e86e00)
$(call add-radio-file-sha1-checked,radio/fsg.img,bee216caa6bd33a926be57e345a5e584d8cae901)
$(call add-radio-file-sha1-checked,radio/hyp.img,a63864126a2ac03bf48c2c1858440e91322f5896)
$(call add-radio-file-sha1-checked,radio/keymaster.img,fbaaf440dcbbede3ca4541e4cbfa4cbcc143a7f9)
$(call add-radio-file-sha1-checked,radio/logo.img,18ae9f63f765f7c7ed95cd54649f722c631eca96)
$(call add-radio-file-sha1-checked,radio/prov.img,b23bce3dfec2553556faabca93498774bf856db4)
$(call add-radio-file-sha1-checked,radio/qupfw.img,5fe8e685c5b84066bbacec4788aa24763ceea9b4)
$(call add-radio-file-sha1-checked,radio/shrm.img,4eb2c486787e1613c9c50a1fa0d396ce9507c43e)
$(call add-radio-file-sha1-checked,radio/storsec.img,2b02fd23d2e8d1424b3e0371a5f7c31e33829ee1)
$(call add-radio-file-sha1-checked,radio/tz.img,357fcb70904abc8f2d25537b8982bcd311d293d8)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,dfc974f09ac18a62d5f3b06eb7ce5728ea4b1c9b)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,0352832c23eb66885579f0a3c2dea35281c40828)
$(call add-radio-file-sha1-checked,radio/xbl.img,02e55a50762d6a4d8368d3bb09e1dbe3c061b0b7)

endif
